/** Shared lavender / plum palette for homepage marketing sections. */
export const MARKETING_PURPLE = {
  sectionBg: "bg-[#f9f9fb] dark:bg-background",
  heading: "text-[#6d5b8e] dark:text-[#c4b8dc]",
  title: "text-[#4a3d62] dark:text-foreground",
  subtitle: "text-[#8b7fa8] dark:text-muted-foreground",
  iconBg: "bg-[#ede9f5] dark:bg-primary/15",
  icon: "text-[#6d5b8e] dark:text-primary",
  cardBorder: "border-black/[0.06] dark:border-border",
  cardSurface: "bg-white dark:bg-card",
  cardInner: "bg-[#f5f3fa] dark:bg-muted",
  accent: "bg-[#6d5b8e] dark:bg-primary",
  accentMuted: "bg-[#8b7fa8]/35 hover:bg-[#8b7fa8]/55",
  accentBorder: "border-[#6d5b8e]/25 dark:border-primary/40",
  accentText: "text-[#6d5b8e] dark:text-primary",
  accentHover: "hover:bg-[#ede9f5] dark:hover:bg-primary/10",
  spotlightTop: "bg-[#6d5b8e]/12 dark:bg-primary/10",
  spotlightBottom: "bg-[#8574a8]/20 dark:bg-primary/15",
  focusRing: "focus-within:ring-[#6d5b8e]/30 dark:focus-within:ring-primary/40",
  activeCardRing: "ring-2 ring-[#6d5b8e]/30 dark:ring-primary/35",
  affiliate: "bg-[#8574a8] dark:bg-primary",
  affiliateButton: "text-[#8574a8] dark:text-primary",
} as const;
